apiVersion: v1
kind: Service

metadata:
  name: notesappsvc
  namespace: notesapp

#Service spec
spec:
  selector:
    app: notesapp #Must match the labels defined in the deployment pod template
  ports:
    - protocol: TCP
      port: 8001  # Can be any port number we assign here to expose the service & map it with system port to access the service from outside the cluster
      targetPort: 8000  #This should be same as the containerPort where application is listening inside the container
  type: ClusterIP 